title: "Nick McLarty"
contact_email: "nick@inick.net"
profile_photo_url: "https://nick.mclarty.me/images/avatar.jpg"
subtitle: "Information Security Officer in College Station, Texas"
attributes:
  - attribute: "Information Security Officer"
  - attribute: "Cybersecurity Consultant"
  - attribute: "Husband and Father"
  - attribute: "WordPress + Genesis Developer"
  - attribute: "Node.JS Dabbler"
  - attribute: "Starbucks Supporter"
  - attribute: "IPv6 Promoter"
  - attribute: "Pilot"
  - attribute: "Aggie"
  - attribute: "Texan"
social:
  - service: "Facebook"
    fa_class: "fa-facebook"
    url: "https://www.facebook.com/nickmclarty"
    target: "_blank"
  - service: "Twitter"
    fa_class: "fa-twitter"
    url: "https://twitter.com/nmclarty"
    target: "_blank"
  - service: "LinkedIn"
    fa_class: "fa-linkedin"
    url: "https://www.linkedin.com/in/nickmclarty"
    target: "_blank"
  - service: "Google+"
    fa_class: "fa-google-plus"
    url: "https://plus.google.com/+nickmclarty"
    target: "_blank"
  - service: "GitHub"
    fa_class: "fa-github"
    url: "https://github.com/mclarty"
    target: "_blank"
  - service: "Medium"
    fa_class: "fa-medium"
    url: "https://medium.com/@nickmclarty"
    target: "_blank"
  - service: "GPG"
    fa_class: "fa-key"
    url: "https://keybase.io/mclarty"
    target: "_blank"
  - service: "Blog"
    fa_class: "fa-bookmark"
    url: "/blog"
h-card:
  p-name: "Nicholas McLarty"
  p-honorific-prefix: "Mr."
  p-given-name: "Nicholas"
  p-family-name: "McLarty"
  p-honorific-suffix: "CISSP"
  p-nickname: "Nick"
  p-locality: "College Station"
  p-region: "Texas"
  p-country-name: "US"
  p-sex: "M"
sass:
  style: compact
ga_key: "UA-104126534-1"
