title: "Nick McLarty"
subtitle: "Information Security Officer in College Station, Texas"
attributes:
  - attribute: "Information Security Officer"
  - attribute: "Cybersecurity Consultant"
  - attribute: "Husband and Father"
  - attribute: "WordPress + Genesis Developer"
  - attribute: "Node.JS Dabbler"
  - attribute: "Starbucks Supporter"
  - attribute: "IPv6 Promoter"
  - attribute: "Pilot"
  - attribute: "Aggie"
  - attribute: "Texan"
social:
  - service: "Facebook"
    fa_class: "fa-facebook"
    url: "https://www.facebook.com/nickmclarty"
  - service: "Twitter"
    fa_class: "fa-twitter"
    url: "https://twitter.com/nmclarty"
  - service: "LinkedIn"
    fa_class: "fa-linkedin"
    url: "https://www.linkedin.com/in/nickmclarty"
  - service: "Google+"
    fa_class: "fa-google-plus"
    url: "https://plus.google.com/+nickmclarty"
  - service: "GitHub"
    fa_class: "fa-github"
    url: "https://github.com/mclarty"
  - service: "Medium"
    fa_class: "fa-medium"
    url: "https://medium.com/@nickmclarty"
sass:
  style: compact
